import { Component } from '@angular/core';

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html',
  styleUrls: ['./board.component.css']
})
export class BoardComponent {
  board = [{
    "digits": [
      {"number": 1, "free": true},
      {"number": 3, "free": false},
      {"number": 7, "free": false},
      {"number": 1, "free": false},
      {"number": 2, "free": false},
      {"number": 2, "free": false},
      {"number": 1, "free": false},
      {"number": 8, "free": false},
      {"number": 6, "free": false},
      {"number": 5, "free": true},
      {"number": 5, "free": true},
      {"number": 6, "free": false},
      {"number": 2, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      {"number": 1, "free": false},
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ]
  }];

}
